INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Computador A', 'I7 16GB SSD1T', 5403);
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Computador B', 'I7 16GB SSD2T', 6403);
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ('Computador C', 'I7 16GB SSD2T', 1234);
--testar o insert no banco h2 pra ver se funciona primeiro


INSERT INTO TBL_CLIENT (DATACADASTRO, DOC, EMAIL, NAME) VALUES ('26/08/2007','122414215125', 'vitorson@', 'vitor');

